import productType, { productCardType } from "@/types/product";

export let Products: productCardType[] = [
  {
    _id: "1",
    images: ["/iphone12.jpg", "/iphone12.jpg"],
    likes: 101,
    name: "Iphone 12",
    price: 1100,
    category: "Moblie Phones",
  },
  {
    _id: "2",
    images: [
      "/laptop1.jpg",
      "/laptop2.jpg",
      "/laptop1.jpg",
      "/laptop2.jpg",
    ],
    likes: 2012,
    name: "Dell Optiplex 12032",
    price: 600,
    category: "Category Name",
  },
  {
    _id: "3",
    images: [
      "/macbook.jpg",
      "/macbook2.jpg",
      "/macbook3.jpg",
    ],
    likes: 2012,
    name: "Apple MacBook Air",
    price: 1699,
    category: "Category Name",
  },
  {
    _id: "1",
    images: ["/iphone12.jpg", "/iphone12.jpg"],
    likes: 101,
    name: "Iphone 12",
    price: 1100,
    category: "Category Name",
  },
  {
    _id: "2",
    images: [
      "/laptop1.jpg",
      "/laptop2.jpg",
      "/laptop1.jpg",
      "/laptop2.jpg",
    ],
    likes: 2012,
    name: "Dell Optiplex 12032",
    price: 600,
    category: "Category Name",
  },
  {
    _id: "3",
    images: [
      "/macbook.jpg",
      "/macbook2.jpg",
      "/macbook3.jpg",
    ],
    likes: 2012,
    name: "Apple MacBook Air",
    price: 1699,
    category: "Category Name",
  },
  {
    _id: "1",
    images: ["/iphone12.jpg", "/iphone12.jpg"],
    likes: 101,
    name: "Iphone 12",
    price: 1100,
    category: "Category Name",
  },
  {
    _id: "2",
    images: [
      "/laptop1.jpg",
      "/laptop2.jpg",
      "/laptop1.jpg",
      "/laptop2.jpg",
    ],
    likes: 2012,
    name: "Dell Optiplex 12032",
    price: 600,
    category: "Category Name",
  },
  {
    _id: "3",
    images: [
      "/macbook.jpg",
      "/macbook2.jpg",
      "/macbook3.jpg",
    ],
    likes: 2012,
    name: "Apple MacBook Air",
    price: 1699,
    category: "Category Name",
  },
  {
    _id: "1",
    images: ["/iphone12.jpg", "/iphone12.jpg"],
    likes: 101,
    name: "Iphone 12",
    price: 1100,
    category: "Category Name",
  },
  {
    _id: "2",
    images: [
      "/laptop1.jpg",
      "/laptop2.jpg",
      "/laptop1.jpg",
      "/laptop2.jpg",
    ],
    likes: 2012,
    name: "Dell Optiplex 12032",
    price: 600,
    category: "Category Name",
  },
  {
    _id: "3",
    images: [
      "/macbook.jpg",
      "/macbook2.jpg",
      "/macbook3.jpg",
    ],
    likes: 2012,
    name: "Apple MacBook Air",
    price: 1699,
    category: "Category Name",
  },
];

export let staticProduct: productType = {
  _id: "3",
  images: [
    "/macbook.jpg",
    "/macbook2.jpg",
    "/macbook3.jpg",
  ],
  likes: 2012,
  name: "Apple MacBook Air",
  price: 1699,
  category: "Laptops and Pcs",
  discription: `this is testing discription .
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut illo consequuntur odit optio nam, voluptatibus officia. Qui, ut unde facilis dolore doloremque nulla, pariatur cumque sit repellendus, reiciendis odit ratione saepe delectus quasi amet autem magni ullam! Sunt deleniti eum ipsum enim ipsa inventore mollitia soluta illum odit fugiat saepe eos, et provident in incidunt dolorum laudantium ea minima nostrum reprehenderit repellendus, cumque, commodi quos. Delectus porro optio expedita earum. Velit consequuntur recusandae impedit quo, animi quia beatae quae nobis odit? Illum deserunt adipisci dolor libero sit, officia veritatis nostrum! Perferendis totam culpa inventore commodi similique ratione mollitia asperiores accusantium eaque, at fugiat pariatur aperiam doloribus, assumenda ad nobis. Nisi rem voluptates et ullam cum! Quod, quas vero? Sint sunt sapiente doloribus magni nemo natus, deserunt consectetur repudiandae aspernatur necessitatibus commodi voluptatem! Minus architecto inventore pariatur accusamus nostrum amet praesentium facere facilis cupiditate ea esse vero hic officia quia corporis voluptates odio maxime molestias itaque, debitis velit laboriosam impedit, est veritatis. Alias assumenda quam deserunt nam laborum, autem impedit explicabo quas, sunt numquam laudantium officia perspiciatis reiciendis, dolorem sit beatae deleniti vero! Quo dolore dignissimos dolorem, in consectetur earum iure nobis tenetur, delectus tempora ipsum quas placeat molestias totam pariatur?
    `,
  inStock: 101,
  owner: {
    firstName: "Azhar",
    lastName: " Lone",
    profilePic: "",
    userName: "azhar-lone",
    _id: "1",
  },
  createdAt: new Date(Date.now()),
  updatedAt: new Date(Date.now()),
};
